### PR TITLE
Add FR translation on new strings

### PR DESCRIPTION
**Pull request by werdeil**
Hi @AF-1

Sorry for the delay, here are the translations on the new strings.

I tried to test it but got an issue when clicking on any of the charts, are you aware of this?
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at showchart.min.js:9:1259

### CODE REVIEW

**Comment by AF-1** [comment]
So far I haven't been abled to reproduce this (already using the new FR translations).

Assuming you're using the latest git checkout:
- did you delete your browser cache to get rid of previously cached html and JS files?
- Does the LMS **server** log report any issues? Maybe temporarily set the VS plugin log level to _debug_, load the VS main page and try 1 chart. Then take a look at the server.log again.
- Does this happen with the LMS default skin **and** the Material skin?
- Does it happen in all of your browsers (which ones and what OS)?
- And about your LMS instance: host OS, LMS version,  Perl version?
Here I'm using LMS 8.3 with perl 5.34.

**Comment by werdeil** [comment]
Here are the log I get on the server:
```
[22-05-13 12:11:54.6979] Slim::Utils::Misc::msg (1341) Warning: [12:11:54.6971] Odd number of elements in anonymous hash at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/VisualStatistics/Plugin.pm line 89.
[22-05-13 12:11:54.6985] Plugins::VisualStatistics::Plugin::handleJSON (97) exec time for query "{"list":"decadelist"}" = 0.00129008293151855 seconds.
[22-05-13 12:11:54.7422] Slim::Utils::Misc::msg (1341) Warning: [12:11:54.7413] Odd number of elements in anonymous hash at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/VisualStatistics/Plugin.pm line 89.
[22-05-13 12:11:54.7435] Plugins::VisualStatistics::Plugin::handleJSON (97) exec time for query "{"list":"decadelist"}" = 0.00163984298706055 seconds.
[22-05-13 12:11:57.5080] Slim::Utils::Misc::msg (1341) Warning: [12:11:57.5076] Odd number of elements in anonymous hash at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/VisualStatistics/Plugin.pm line 89.
[22-05-13 12:11:57.5087] Plugins::VisualStatistics::Plugin::handleJSON (97) exec time for query "{"type":"getDataLibStatsText"}" = 0.000925064086914062 seconds.
[22-05-13 12:11:58.6051] Slim::Utils::Misc::msg (1341) Warning: [12:11:58.6046] Odd number of elements in anonymous hash at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/VisualStatistics/Plugin.pm line 89.
```
This happens on all skins, on Chrome and Safari (MacOS)
On host side: Logitech Media Server Version : 8.2.0 (Debian - FR - utf8, x86_64-linux) and Perl : 5.30.0

**Comment by AF-1** [comment]
My Safari + FF = on macOS. My LMS = on maOS. From other users I got this feedback:
- Windows7 with LMS 8.3.0 (May 12, 2022) - works.
- Debian x84 64-linux with LMS 8.2.1 (Apr. 12, 2022), Perl 5.28.1 and FF ESR 91 - works.

Are you using piCorePlayer?

It's really difficult to troubleshoot this if I can't reproduce this. At the very least I need more (detailled) debug messages:
Load the VS main page, **then** (in another browser tab) set the VS log level to **debug** to avoid too many log entires. I'll really have to see all of these debug messages that happen after you've tried to display a chart.
It could also be an encoding problem...

As you will have noticed, the users who reported back used the latest version of 8.2.1 or 8.3.0. I don't have access to older versions. If you're still using 8.2.**0**, do you have a way of testing your setup with 8.2.**1**? Or even 8.**3**.0?

**Comment by werdeil** [comment]
Don't worry, if you don't reproduce I'm pretty sure it is linked to some cache in my setup. I'll try to find what needed to be cleared and reinstall the plugin from scratch. I'll keep you posted tonight.

**Comment by AF-1** [comment]
I've simplified the JSON call part. At the moment, I can't think of anything else. We'll get there eventually. :-)

**Comment by werdeil** [comment]
HI @AF-1 , I manage to make it work, so the issue was when transitioning from current production plugin to the new version.
I updated some lines too. It should be good now.

**Pull request merged**
